language: r

r:
  - release
  - devel

cache: packages

sudo: required

dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

warnings_are_errors: false

r_packages:
  - rgdal
  - roxygen2
  - rmarkdown
  - sf
  - raster
  - gdalUtils
  - tools
  - rgrass7
  - sp
  - RSAGA

after_success:
  - Rscript -e 'covr::codecov()'