base:
   folders: ["data/source", "data/results","data/run", "docs/figures", "tmp"]
   folder_names: NULL
   init_git: true
   code_subfolders: ["src", "src/functions" , "src/config"]
   path_prefix: NULL
   global: false
   libs: ["terra", "stars", "sf" , "RStoolbox", "tmap" , "mapview"]
   create_folders: true
   files: ["main.R", "000-setup.R", "README.qmd"]
baseSpatial:
   folders: ["data/source", "data/results", "data/level0", "data/level1","data/run", "docs/figures", "tmp"]
   folder_names: NULL
   init_git: true
   code_subfolders: ["src", "src/functions" , "src/config"]
   path_prefix: NULL
   global: false
   libs: ["terra", "stars", "sf" , "RStoolbox", "tmap" , "mapview"]
   create_folders: true
   files: ["main.R", "000-setup.R", "README.qmd"]   
advancedSpatial:
   folders: ["data/source", "data/results", "data/level0", "data/level1","data/run", "docs/figures", "tmp"]
   folder_names: NULL
   init_git: true
   code_subfolders: ["src", "src/functions" , "src/config"]
   path_prefix: NULL
   global: false
   libs: ["terra", "stars", "sf" , "RStoolbox", "tmap" , "mapview"]
   create_folders: true
      files: ["main.R", "000-setup.R", "README.qmd"]

