base:
   dataFolder: ["source", "results", "clean", "run"]
   docsFolder: [ "figures"]
   tmpFolder:  ["tmp"]
   init_git: true
   init_renv: true
   code_subfolder: ["src", "src/functions" , "src/config"]
   global: false
   libs: ""
   create_folders: true
   files: [ "pre-processing.R", "post-processing.R", "10-processing.R", "src/functions/000_setup.R" ,"src/main-control.R"]
baseSpatial:
   dataFolder: ["level0", "level1", "level2", "run" ,"aux"]
   docsFolder: [ "figures"]
   tmpFolder:  ["tmp"]
   code_subfolder: ["src", "src/functions" , "src/config"]   
   init_git: true
   init_renv: true   
   global: false
   libs: ["terra", "stars", "sf" , "RStoolbox", "tmap" , "mapview", "dplyr"]
   create_folders: true
   files: [ "pre-processing.R", "post-processing.R", "10-processing.R", "src/functions/000_setup.R" ,"src/main-control.R"]
advancedSpatial:
   dataFolder: ["level0", "level1", "level2", "run"]
   docsFolder: [ "figures"]
   tmpFolder:  ["tmp"]
   code_subfolder: ["src", "src/functions" , "src/config"]
   init_git: true
   init_renv: true   
   global: false
   libs: ["terra", "stars", "sf" , "RStoolbox", "tmap" , "mapview" ,"dplyr", "caret" ,"randomforest"]
   create_folders: true
   files: [ "pre-processing.R", "post-processing.R", "10-processing.R", "src/functions/000_setup.R" ,"src/main-control.R"]
 
          

